// var express=require('express')
// var app=express();
// // get method provide us Routing facility with the help of express
// app.get('',(req,res)=>{
//     res.send("this is home page ")
// })
// app.get('/about',(req,res)=>{
//     res.send("This is about page")
// })
// app.get('/help',(req,res)=>{
// res.send("this is help page")
// })



// app.listen(5000)


//queryparams is the req generated by the client or browser
// var express=require('express')
// var app=express();
// app.get('',(req,res)=>{
//     res.send(`welcome ${req.query.name}`)
// })
// app.listen(5000)


// Routing with Html pages with diffrent files 
// query will pass with file extension
// var express=require('express')
// var path=require('path')
// var app=express();
// var filepath=path.join(__dirname,'Pages')
// app.use(express.static(filepath))
// app.listen(5000);



// Routing with Html pages with diffrent files 
// query will pass without file extension
// var express=require('express')
// var path=require('path')
// var app=express();
// var filepath=path.join(__dirname,'Pages')

// app.get('',(req,res)=>{
//  res.sendFile(`${filepath}/Home.html`)

// })
// app.get('/about',(req,res)=>{
//     res.sendFile(`${filepath}/about.html`)
   
//    })
//    app.get('/contactus',(req,res)=>{
//     res.sendFile(`${filepath}/contactus.html`)
   
//    })
//    app.get('*',(req,res)=>{
//     res.sendFile(`${filepath}/404!.html`)
   
//    })
//      app.listen(5000)


// middleware :it is used for validation and read write or 
//modifications of req and res...
// we can create saparate file for middleware and use in any file

//  const express=require('express')
//  const app=express();
//  const reqfilter=(req,res,next)=>{   
//      //next() is used to process further for routing
//     if(!req.query.age){
//         res.send("Please Provide your Age")
//     }
//      else if(req.query.age<18){
//     res.send("You can't access this page")
//  } else {
//     next();
//  }
// }
//  app.use(reqfilter)

//   app.get('',(req,res)=>{
//     res.send("This is Home page")
//   })
//   app.get('/about',(req,res)=>{
//     res.send("This is About page")
//   })
//   app.get('/Help',(req,res)=>{
//     res.send("This is help page")
//   })
// app.listen(5000) 


//Router level middleware 
 // we can apply middleware on a single file 
  //or group of files 


const express= require('express')
const app=express();
const reqFilter=require('./middleware')
const route=express.Router();

route.use(reqFilter)
  app.get('',(req,res)=>{
    res.send("This is Home page")
  })
  route.get('/about',(req,res)=>{
    res.send("This is About page")
  })
  app.get('/Help',(req,res)=>{
    res.send("This is help page")
  })

app.use('/',route)
app.listen(5000)
